from tkinter import *

root = Tk()
root.title("Chessboard")
root.geometry("400x400+300+300")

# add chess pieces
kingWhite = PhotoImage(file="king_white.gif")

# create chess squares
a1 = Frame(root, bg='white', width=50, height=50)
a2 = Frame(root, bg='grey', width=50, height=50)
a3 = Frame(root, bg='white', width=50, height=50)
a4 = Frame(root, bg='grey', width=50, height=50)
a5 = Frame(root, bg='white', width=50, height=50)
a6 = Frame(root, bg='grey', width=50, height=50)
a7 = Frame(root, bg='white', width=50, height=50)
a8 = Frame(root, bg='grey', width=50, height=50)
b1 = Frame(root, bg='grey', width=50, height=50)
b2 = Frame(root, bg='white', width=50, height=50)
b3 = Frame(root, bg='grey', width=50, height=50)
b4 = Frame(root, bg='white', width=50, height=50)
b5 = Frame(root, bg='grey', width=50, height=50)
b6 = Frame(root, bg='white', width=50, height=50)
b7 = Frame(root, bg='grey', width=50, height=50)
b8 = Frame(root, bg='white', width=50, height=50)

c1 = Frame(root, bg='white', width=50, height=50)
c2 = Frame(root, bg='grey', width=50, height=50)
c3 = Frame(root, bg='white', width=50, height=50)
c4 = Frame(root, bg='grey', width=50, height=50)
c5 = Frame(root, bg='white', width=50, height=50)
c6 = Frame(root, bg='grey', width=50, height=50)
c7 = Frame(root, bg='white', width=50, height=50)
c8 = Frame(root, bg='grey', width=50, height=50)
d1 = Frame(root, bg='grey', width=50, height=50)
d2 = Frame(root, bg='white', width=50, height=50)
d3 = Frame(root, bg='grey', width=50, height=50)
d4 = Frame(root, bg='white', width=50, height=50)
d5 = Frame(root, bg='grey', width=50, height=50)
d6 = Frame(root, bg='white', width=50, height=50)
d7 = Frame(root, bg='grey', width=50, height=50)
d8 = Frame(root, bg='white', width=50, height=50)

e1 = Frame(root, bg='white', width=50, height=50)
e2 = Frame(root, bg='grey', width=50, height=50)
e3 = Frame(root, bg='white', width=50, height=50)
e4 = Frame(root, bg='grey', width=50, height=50)
e5 = Frame(root, bg='white', width=50, height=50)
e6 = Frame(root, bg='grey', width=50, height=50)
e7 = Frame(root, bg='white', width=50, height=50)
e8 = Frame(root, bg='grey', width=50, height=50)
f1 = Frame(root, bg='grey', width=50, height=50)
f2 = Frame(root, bg='white', width=50, height=50)
f3 = Frame(root, bg='grey', width=50, height=50)
f4 = Frame(root, bg='white', width=50, height=50)
f5 = Frame(root, bg='grey', width=50, height=50)
f6 = Frame(root, bg='white', width=50, height=50)
f7 = Frame(root, bg='grey', width=50, height=50)
f8 = Frame(root, bg='white', width=50, height=50)

g1 = Frame(root, bg='white', width=50, height=50)
g2 = Frame(root, bg='grey', width=50, height=50)
g3 = Frame(root, bg='white', width=50, height=50)
g4 = Frame(root, bg='grey', width=50, height=50)
g5 = Frame(root, bg='white', width=50, height=50)
g6 = Frame(root, bg='grey', width=50, height=50)
g7 = Frame(root, bg='white', width=50, height=50)
g8 = Frame(root, bg='grey', width=50, height=50)
h1 = Frame(root, bg='grey', width=50, height=50)
h2 = Frame(root, bg='white', width=50, height=50)
h3 = Frame(root, bg='grey', width=50, height=50)
h4 = Frame(root, bg='white', width=50, height=50)
h5 = Frame(root, bg='grey', width=50, height=50)
h6 = Frame(root, bg='white', width=50, height=50)
h7 = Frame(root, bg='grey', width=50, height=50)
h8 = Frame(root, bg='white', width=50, height=50)

# lay them out on the board
root.grid_rowconfigure(8, weight=1)
root.grid_columnconfigure(8, weight=1)

a1.grid(row=1, column=1, sticky="ew")
a2.grid(row=1, column=2, sticky="ew")
a3.grid(row=1, column=3, sticky="ew")
a4.grid(row=1, column=4, sticky="ew")
a5.grid(row=1, column=5, sticky="ew")
a6.grid(row=1, column=6, sticky="ew")
a7.grid(row=1, column=7, sticky="ew")
a8.grid(row=1, column=8, sticky="ew")
b1.grid(row=2, column=1, sticky="ew")
b2.grid(row=2, column=2, sticky="ew")
b3.grid(row=2, column=3, sticky="ew")
b4.grid(row=2, column=4, sticky="ew")
b5.grid(row=2, column=5, sticky="ew")
b6.grid(row=2, column=6, sticky="ew")
b7.grid(row=2, column=7, sticky="ew")
b8.grid(row=2, column=8, sticky="ew")

c1.grid(row=3, column=1, sticky="ew")
c2.grid(row=3, column=2, sticky="ew")
c3.grid(row=3, column=3, sticky="ew")
c4.grid(row=3, column=4, sticky="ew")
c5.grid(row=3, column=5, sticky="ew")
c6.grid(row=3, column=6, sticky="ew")
c7.grid(row=3, column=7, sticky="ew")
c8.grid(row=3, column=8, sticky="ew")
d1.grid(row=4, column=1, sticky="ew")
d2.grid(row=4, column=2, sticky="ew")
d3.grid(row=4, column=3, sticky="ew")
d4.grid(row=4, column=4, sticky="ew")
d5.grid(row=4, column=5, sticky="ew")
d6.grid(row=4, column=6, sticky="ew")
d7.grid(row=4, column=7, sticky="ew")
d8.grid(row=4, column=8, sticky="ew")

e1.grid(row=5, column=1, sticky="ew")
e2.grid(row=5, column=2, sticky="ew")
e3.grid(row=5, column=3, sticky="ew")
e4.grid(row=5, column=4, sticky="ew")
e5.grid(row=5, column=5, sticky="ew")
e6.grid(row=5, column=6, sticky="ew")
e7.grid(row=5, column=7, sticky="ew")
e8.grid(row=5, column=8, sticky="ew")
f1.grid(row=6, column=1, sticky="ew")
f2.grid(row=6, column=2, sticky="ew")
f3.grid(row=6, column=3, sticky="ew")
f4.grid(row=6, column=4, sticky="ew")
f5.grid(row=6, column=5, sticky="ew")
f6.grid(row=6, column=6, sticky="ew")
f7.grid(row=6, column=7, sticky="ew")
f8.grid(row=6, column=8, sticky="ew")

g1.grid(row=7, column=1, sticky="ew")
g2.grid(row=7, column=2, sticky="ew")
g3.grid(row=7, column=3, sticky="ew")
g4.grid(row=7, column=4, sticky="ew")
g5.grid(row=7, column=5, sticky="ew")
g6.grid(row=7, column=6, sticky="ew")
g7.grid(row=7, column=7, sticky="ew")
g8.grid(row=7, column=8, sticky="ew")
h1.grid(row=8, column=1, sticky="ew")
h2.grid(row=8, column=2, sticky="ew")
h3.grid(row=8, column=3, sticky="ew")
h4.grid(row=8, column=4, sticky="ew")
h5.grid(row=8, column=5, sticky="ew")
h6.grid(row=8, column=6, sticky="ew")
h7.grid(row=8, column=7, sticky="ew")
h8.grid(row=8, column=8, sticky="ew")

root.mainloop()
